export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUBCATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCEEDED = "GET_CATEGORIES_SUCCEEDED";
export const GET_SUBCATEGORIES_SUCCEEDED = "GET_CATEGORIES_SUCCEEDED";
