export const GET_ROOTITEMS = "GET_ROOTITEMS";
export const GET_ITEMS = "GET_ITEMS";
export const GET_ROOTITEMS_SUCCEEDED = "GET_ROOTITEMS_SUCCEEDED";
export const GET_ITEMS_SUCCEEDED = "GET_ITEMS_SUCCEEDED";
